In [1]:
import torch

x = torch.arange(12).reshape(3, 4)
print(x)
print(x.shape)
print(x[0])
print(x[:, 1])
print(x.sum())
print(x.float().mean())

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])
torch.Size([3, 4])
tensor([0, 1, 2, 3])
tensor([1, 5, 9])
tensor(66)
tensor(5.5000)
