# 06 线性代数最小集

本节练习最常用的线性代数概念：向量、矩阵、点积、矩阵乘法、范数。

输出目标：

- 用 PyTorch 实现点积
- 用 PyTorch 实现矩阵乘法
- 用 PyTorch 实现 L2 范数
- 写出每一步的 shape 变化

## 1. 最小概念

- 向量：一维张量，例如 shape 是 `(3,)` 的 `[1, 2, 3]`
- 矩阵：二维张量，例如 shape 是 `(2, 3)` 的 2 行 3 列数据
- 点积：两个长度相同的向量，对应位置相乘后求和，结果是一个标量
- 矩阵乘法：左矩阵的列数必须等于右矩阵的行数，例如 `(2, 3) @ (3, 4) -> (2, 4)`
- L2 范数：向量长度，计算方式是先平方、再求和、再开方

In [4]:
import torch

torch.set_printoptions(precision=2)


def shape_of(x):
    return tuple(x.shape)


def show(name, value):
    print(f"{name}:")
    print(value)
    print(f"shape = {shape_of(value)}\n")

## 2. 向量和矩阵

先创建两个向量和两个矩阵，后面的点积、矩阵乘法、范数都基于它们。

In [5]:
x = torch.tensor([1.0, 2.0, 3.0])
y = torch.tensor([4.0, 5.0, 6.0])

A = torch.arange(1, 7, dtype=torch.float32).reshape(2, 3)
B = torch.arange(1, 13, dtype=torch.float32).reshape(3, 4)

show("向量 x", x)
show("向量 y", y)
show("矩阵 A", A)
show("矩阵 B", B)

向量 x:
tensor([1., 2., 3.])
shape = (3,)

向量 y:
tensor([4., 5., 6.])
shape = (3,)

矩阵 A:
tensor([[1., 2., 3.],
        [4., 5., 6.]])
shape = (2, 3)

矩阵 B:
tensor([[ 1.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.],
        [ 9., 10., 11., 12.]])
shape = (3, 4)



## 3. 点积

点积公式：

`x · y = x1*y1 + x2*y2 + ... + xn*yn`

shape 变化：`(3,) · (3,) -> ()`，两个向量变成一个标量。

In [7]:
dot_manual = (x * y).sum()
dot_torch = torch.dot(x, y)

print("x * y:", x * y)
print("手动点积:", dot_manual)
print("torch.dot:", dot_torch)
print(f"shape 变化: {shape_of(x)} · {shape_of(y)} -> {shape_of(dot_manual)}")

assert torch.allclose(dot_manual, dot_torch)

x * y: tensor([ 4., 10., 18.])
手动点积: tensor(32.)
torch.dot: tensor(32.)
shape 变化: (3,) · (3,) -> ()


## 4. 矩阵乘法

矩阵乘法要求左边矩阵的列数等于右边矩阵的行数。

这里 `A` 的 shape 是 `(2, 3)`，`B` 的 shape 是 `(3, 4)`，中间的 `3` 可以对齐，所以结果 shape 是 `(2, 4)`。

In [8]:
C = A @ B
C_torch = torch.matmul(A, B)

show("A @ B", C)
print(f"shape 变化: {shape_of(A)} @ {shape_of(B)} -> {shape_of(C)}")

assert torch.allclose(C, C_torch)

A @ B:
tensor([[ 38.,  44.,  50.,  56.],
        [ 83.,  98., 113., 128.]])
shape = (2, 4)

shape 变化: (2, 3) @ (3, 4) -> (2, 4)


## 5. L2 范数

L2 范数可以理解为向量的长度。

公式：

`||x||2 = sqrt(x1^2 + x2^2 + ... + xn^2)`

shape 变化：`(3,) -> ()`，一个向量变成一个标量。

In [9]:
l2_manual = torch.sqrt((x ** 2).sum())
l2_torch = torch.linalg.vector_norm(x, ord=2)

print("x ** 2:", x ** 2)
print("手动 L2 范数:", l2_manual)
print("torch.linalg.vector_norm:", l2_torch)
print(f"shape 变化: {shape_of(x)} -> {shape_of(l2_manual)}")

assert torch.allclose(l2_manual, l2_torch)

x ** 2: tensor([1., 4., 9.])
手动 L2 范数: tensor(3.74)
torch.linalg.vector_norm: tensor(3.74)
shape 变化: (3,) -> ()


## 小结

- 点积：`(n,) · (n,) -> ()`
- 矩阵乘法：`(m, n) @ (n, p) -> (m, p)`
- L2 范数：`(n,) -> ()`

记 shape 时，可以先看维度是否能对齐，再看结果会剩下什么维度。